#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Encode-HanExtra
version:      0.08
version_from: HanExtra.pm
installdirs:  site
requires:
    Encode:                        1.41

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
